### ISSUE TITLE
raise RuntimeError('Timeout during packet send')

### ISSUE THREAD

**Issue by pierrot10** [adafruit/Adafruit_CircuitPython_TinyLoRa#21]
Hello

I have followed that procedure to use TinyLora with a Raspberry Zero to send data to the Thing network TTN with LoRaWAN
[https://learn.adafruit.com/lora-and-lorawan-radio-for-raspberry-pi/usage](https://learn.adafruit.com/lora-and-lorawan-radio-for-raspberry-pi/usage)

All went well, excepted when I send the data, I always get that error even if TTN receive the message

> Sending periodic data...
> Traceback (most recent call last):
>   File "radio_lorawan.py", line 114, in <module>
>     send_pi_data_periodic()
>   File "radio_lorawan.py", line 70, in send_pi_data_periodic
>     send_pi_data(CPU)
>   File "radio_lorawan.py", line 80, in send_pi_data
>     lora.send_data(data_pkt, len(data_pkt), lora.frame_counter)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_tinylora/adafruit_tinylora.py", line 234, in send_data
>     self.send_packet(lora_pkt, lora_pkt_len, timeout)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_tinylora/adafruit_tinylora.py", line 275, in send_packet
>     raise RuntimeError('Timeout during packet send')
> RuntimeError: Timeout during packet send

I looked at TTN console and each time the Raspberry send a message, I can see that my devise has been seen 1 second ago.
But my Phyton script return alway the above message instead of

> Data sent!

I spend about 3 hours to understand why. I have my own gateway is in my flat, at 1m of the nodes and I just totaly reinstall the gateway.
In TTN console, the gateway is connected and seen.

I am based in Switzerland then I changed that line:

`ttn_config = TTN(devaddr, nwkey, app, country='EU')`

Any idea how I can debug and solve it?

By the way if you can tell me how I can display the power of signal when the message is sent, that would be GREAT.
My goal is to prepare a simple node and when I start moving away from my gateway, I would like to be able to read the power of the signal until I am too far from the gateway range. At this time the node should display "gateway lost" because it can not reach the gateway anymore.

That the only objectif of my Raspberry/TinyLoRa, but first I have to make sure that when I send a message, even if the message is receive at TTN, I do not have that message any more.

>   File "/usr/local/lib/python3.5/dist-packages/adafruit_tinylora/adafruit_tinylora.py", line 234, in send_data
>     self.send_packet(lora_pkt, lora_pkt_len, timeout)
>   File "/usr/local/lib/python3.5/dist-packages/adafruit_tinylora/adafruit_tinylora.py", line 275, in send_packet
>     raise RuntimeError('Timeout during packet send')
> RuntimeError: Timeout during packet send

Thank a lot and have a good evening

**Comment by pierrot10** [comment]
The problem were due to a bad configuration of the IRQ pin
